import React from "react";

const LeaguesPage = () => {
  return <div>leagues</div>;
};

export default LeaguesPage;

// const data: FixtureData = {
//   fixture: [
//     {
//       id: "6080",
//       team1_id: "246",
//       team2_id: "820",
//       game_date: "2024-11-23",
//       team1_name: "KCB 15s",
//       team2_name: "South Coast Pirates",
//       game_status: "FT",
//       minute: "89",
//       second: "13",
//       game_moment: "secondhalf",
//       league: "Kenya Cup",
//       matchday: "1",
//       fixture_type: "rugby15",
//       live: "1",
//       teamview: "1",
//       series: "30",
//       leagueid: "163",
//       home_score: "0",
//       away_score: "0",
//       winner: null,
//       start_app: "1",
//       hybrid: "0",
//       hybridhome: null,
//       hybridaway: null,
//       lite: "0",
//       location_id: "0",
//       category: "7",
//       groupid: "1",
//       matchtime: "15:00",
//       tmvplayer: "0",
//     },
//   ],
//   home: {
//     "Forward pass": {
//       event_id: "40",
//       name: "Forward pass",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Knock on": {
//       event_id: "41",
//       name: "Knock on",
//       total: "8",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Tackle: {
//       event_id: "42",
//       name: "Tackle",
//       total: "38",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "56",
//           subeventname: "Positive",
//           totalsubevent: "31",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "57",
//           subeventname: "Negative",
//           totalsubevent: "7",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "139",
//           subeventname: "Held up",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Missed tackle": {
//       event_id: "43",
//       name: "Missed tackle",
//       total: "4",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Carries: {
//       event_id: "44",
//       name: "Carries",
//       total: "60",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "357",
//           subeventname: "Own 22",
//           totalsubevent: "3",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "358",
//           subeventname: "Own 50",
//           totalsubevent: "18",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "359",
//           subeventname: "Opponents 50",
//           totalsubevent: "29",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "360",
//           subeventname: "Opponents 22",
//           totalsubevent: "10",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Turnover: {
//       event_id: "45",
//       name: "Turnover",
//       total: "8",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "211",
//           subeventname: "Ruck turnover",
//           totalsubevent: "5",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "212",
//           subeventname: "Pass Intercept",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "213",
//           subeventname: "Ball steal",
//           totalsubevent: "3",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Penalties conceded": {
//       event_id: "46",
//       name: "Penalties conceded",
//       total: "3",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "123",
//           subeventname: "Holding on",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "124",
//           subeventname: "Not Releasing",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "125",
//           subeventname: "offside",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "126",
//           subeventname: "Dangerous Tackle",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "127",
//           subeventname: "Line out Penalty",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "128",
//           subeventname: "Not rolling away",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "129",
//           subeventname: "Scrum Penalty",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "130",
//           subeventname: "Obstruction",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "131",
//           subeventname: "Cynical",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "132",
//           subeventname: "Repeated infringement",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "133",
//           subeventname: "Diving in ruck",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "134",
//           subeventname: "Off feet",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "135",
//           subeventname: "Hands in the ruck",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "136",
//           subeventname: "Late charge on kicker",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "137",
//           subeventname: "intentional taping",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "138",
//           subeventname: "Ball not travelling straight  in a lineout",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "140",
//           subeventname: "Side Entry ",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "199",
//           subeventname: "Double movement",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "206",
//           subeventname: "Elbow In Carry",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "313",
//           subeventname: "Late Tackle",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "314",
//           subeventname: "Tackle without the ball",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "315",
//           subeventname: "Time wasting",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "316",
//           subeventname: "Collapsing maul",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "317",
//           subeventname: "Numbers in the lineout",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Linebreak: {
//       event_id: "47",
//       name: "Linebreak",
//       total: "22",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Score: {
//       event_id: "49",
//       name: "Score",
//       total: "28",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "42",
//           subeventname: "Missed Conversion",
//           totalsubevent: "5",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "43",
//           subeventname: "Successful Drop Goal",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "44",
//           subeventname: "Successful Penalty",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "60",
//           subeventname: "Successful Conversion",
//           totalsubevent: "9",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "61",
//           subeventname: "Missed Penalty",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "62",
//           subeventname: "Missed Drop Goal",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "66",
//           subeventname: "Try",
//           totalsubevent: "14",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "200",
//           subeventname: "Penalty Try",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Lineout: {
//       event_id: "50",
//       name: "Lineout",
//       total: "12",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "40",
//           subeventname: "Won",
//           totalsubevent: "10",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "41",
//           subeventname: "Lost",
//           totalsubevent: "2",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "65",
//           subeventname: "Stolen",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Scrum: {
//       event_id: "51",
//       name: "Scrum",
//       total: "7",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "38",
//           subeventname: "Won",
//           totalsubevent: "6",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "39",
//           subeventname: "Lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "58",
//           subeventname: "Stolen",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Substitute: {
//       event_id: "52",
//       name: "Substitute",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Card: {
//       event_id: "55",
//       name: "Card",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "45",
//           subeventname: "Red",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "46",
//           subeventname: "Yellow",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Incomplete Pass": {
//       event_id: "87",
//       name: "Incomplete Pass",
//       total: "7",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Touch/Take": {
//       event_id: "90",
//       name: "Touch/Take",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Pass: {
//       event_id: "91",
//       name: "Pass",
//       total: "153",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Offload: {
//       event_id: "92",
//       name: "Offload",
//       total: "13",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Lost ball in carry": {
//       event_id: "103",
//       name: "Lost ball in carry",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Visit in opponents 22": {
//       event_id: "104",
//       name: "Visit in opponents 22",
//       total: "12",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Kick for territory": {
//       event_id: "105",
//       name: "Kick for territory",
//       total: "22",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "158",
//           subeventname: "Caught",
//           totalsubevent: "6",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "159",
//           subeventname: "Straight out",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "164",
//           subeventname: "Retrieved",
//           totalsubevent: "2",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "165",
//           subeventname: "50-22",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "166",
//           subeventname: "Lineout",
//           totalsubevent: "12",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "185",
//           subeventname: "Dead Ball",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "186",
//           subeventname: "Knocked On",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "202",
//           subeventname: "Charged Down",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "340",
//           subeventname: "Half time",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "341",
//           subeventname: "Full Time",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Ruck: {
//       event_id: "108",
//       name: "Ruck",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "334",
//           subeventname: "Less Than 3 Sec",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "335",
//           subeventname: "More Than 3 Sec",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Penalty Gain": {
//       event_id: "124",
//       name: "Penalty Gain",
//       total: "13",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "173",
//           subeventname: "Kick",
//           totalsubevent: "8",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "174",
//           subeventname: "Tap",
//           totalsubevent: "4",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "183",
//           subeventname: "Scrum",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "184",
//           subeventname: "Points",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Step out": {
//       event_id: "129",
//       name: "Step out",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Charge Down": {
//       event_id: "130",
//       name: "Charge Down",
//       total: "0",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Restart: {
//       event_id: "133",
//       name: "Restart",
//       total: "13",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "247",
//           subeventname: "kick off reception won",
//           totalsubevent: "11",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "248",
//           subeventname: "kick off reception lost",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "249",
//           subeventname: "kick off retrieval won",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "250",
//           subeventname: "kick off retrieval lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "251",
//           subeventname: "false kick off",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "252",
//           subeventname: "goal line drop out reception won",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "253",
//           subeventname: "goal line drop out reception lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "254",
//           subeventname: "goal line drop out retrieval won",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "255",
//           subeventname: "goal line drop out retrieval lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "256",
//           subeventname: "goal line drop out straight out",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "257",
//           subeventname: "22 drop out reception won",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "258",
//           subeventname: "22 drop out reception lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "259",
//           subeventname: "22 drop out retrieval won",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "260",
//           subeventname: "22 drop out retrieval lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "261",
//           subeventname: "22 drop out straight out",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Visit in own 22": {
//       event_id: "139",
//       name: "Visit in own 22",
//       total: "2",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Maul: {
//       event_id: "146",
//       name: "Maul",
//       total: "2",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "328",
//           subeventname: "Successful",
//           totalsubevent: "2",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "329",
//           subeventname: "Unsuccessful",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Lineout throw": {
//       event_id: "151",
//       name: "Lineout throw",
//       total: "14",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "377",
//           subeventname: "Front won",
//           totalsubevent: "2",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "378",
//           subeventname: "Middle won",
//           totalsubevent: "4",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "379",
//           subeventname: "Back won",
//           totalsubevent: "7",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "380",
//           subeventname: "Front lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "381",
//           subeventname: "Middle lost",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "382",
//           subeventname: "Back lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "391",
//           subeventname: "Overthrow Won",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "392",
//           subeventname: "Overthrow Lost",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Kick Reception": {
//       event_id: "158",
//       name: "Kick Reception",
//       total: "15",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "409",
//           subeventname: "Caught",
//           totalsubevent: "9",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "410",
//           subeventname: "Knocked On",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "411",
//           subeventname: "Knocked Back",
//           totalsubevent: "2",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "412",
//           subeventname: "Missed",
//           totalsubevent: "4",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Lineout Pass to Receiver": {
//       event_id: "162",
//       name: "Lineout Pass to Receiver",
//       total: "9",
//       team: "246",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "419",
//           subeventname: "Complete",
//           totalsubevent: "8",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "420",
//           subeventname: "InComplete",
//           totalsubevent: "0",
//           team: "246",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "421",
//           subeventname: "No Pass",
//           totalsubevent: "1",
//           team: "246",
//           gameidid: "6080",
//         },
//       ],
//     },
//   },
//   away: {
//     "Forward pass": {
//       event_id: "40",
//       name: "Forward pass",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Knock on": {
//       event_id: "41",
//       name: "Knock on",
//       total: "9",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Tackle: {
//       event_id: "42",
//       name: "Tackle",
//       total: "116",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "56",
//           subeventname: "Positive",
//           totalsubevent: "12",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "57",
//           subeventname: "Negative",
//           totalsubevent: "104",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "139",
//           subeventname: "Held up",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Missed tackle": {
//       event_id: "43",
//       name: "Missed tackle",
//       total: "45",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Carries: {
//       event_id: "44",
//       name: "Carries",
//       total: "57",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "357",
//           subeventname: "Own 22",
//           totalsubevent: "8",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "358",
//           subeventname: "Own 50",
//           totalsubevent: "15",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "359",
//           subeventname: "Opponents 50",
//           totalsubevent: "19",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "360",
//           subeventname: "Opponents 22",
//           totalsubevent: "15",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Turnover: {
//       event_id: "45",
//       name: "Turnover",
//       total: "8",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "211",
//           subeventname: "Ruck turnover",
//           totalsubevent: "3",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "212",
//           subeventname: "Pass Intercept",
//           totalsubevent: "3",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "213",
//           subeventname: "Ball steal",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Penalties conceded": {
//       event_id: "46",
//       name: "Penalties conceded",
//       total: "16",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "123",
//           subeventname: "Holding on",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "124",
//           subeventname: "Not Releasing",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "125",
//           subeventname: "offside",
//           totalsubevent: "5",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "126",
//           subeventname: "Dangerous Tackle",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "127",
//           subeventname: "Line out Penalty",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "128",
//           subeventname: "Not rolling away",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "129",
//           subeventname: "Scrum Penalty",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "130",
//           subeventname: "Obstruction",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "131",
//           subeventname: "Cynical",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "132",
//           subeventname: "Repeated infringement",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "133",
//           subeventname: "Diving in ruck",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "134",
//           subeventname: "Off feet",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "135",
//           subeventname: "Hands in the ruck",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "136",
//           subeventname: "Late charge on kicker",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "137",
//           subeventname: "intentional taping",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "138",
//           subeventname: "Ball not travelling straight  in a lineout",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "140",
//           subeventname: "Side Entry ",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "199",
//           subeventname: "Double movement",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "206",
//           subeventname: "Elbow In Carry",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "313",
//           subeventname: "Late Tackle",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "314",
//           subeventname: "Tackle without the ball",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "315",
//           subeventname: "Time wasting",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "316",
//           subeventname: "Collapsing maul",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "317",
//           subeventname: "Numbers in the lineout",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Linebreak: {
//       event_id: "47",
//       name: "Linebreak",
//       total: "2",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Score: {
//       event_id: "49",
//       name: "Score",
//       total: "3",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "42",
//           subeventname: "Missed Conversion",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "43",
//           subeventname: "Successful Drop Goal",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "44",
//           subeventname: "Successful Penalty",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "60",
//           subeventname: "Successful Conversion",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "61",
//           subeventname: "Missed Penalty",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "62",
//           subeventname: "Missed Drop Goal",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "66",
//           subeventname: "Try",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "200",
//           subeventname: "Penalty Try",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Lineout: {
//       event_id: "50",
//       name: "Lineout",
//       total: "9",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "40",
//           subeventname: "Won",
//           totalsubevent: "7",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "41",
//           subeventname: "Lost",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "65",
//           subeventname: "Stolen",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Scrum: {
//       event_id: "51",
//       name: "Scrum",
//       total: "9",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "38",
//           subeventname: "Won",
//           totalsubevent: "8",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "39",
//           subeventname: "Lost",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "58",
//           subeventname: "Stolen",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Substitute: {
//       event_id: "52",
//       name: "Substitute",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Card: {
//       event_id: "55",
//       name: "Card",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "45",
//           subeventname: "Red",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "46",
//           subeventname: "Yellow",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Incomplete Pass": {
//       event_id: "87",
//       name: "Incomplete Pass",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Touch/Take": {
//       event_id: "90",
//       name: "Touch/Take",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Pass: {
//       event_id: "91",
//       name: "Pass",
//       total: "48",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Offload: {
//       event_id: "92",
//       name: "Offload",
//       total: "1",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Lost ball in carry": {
//       event_id: "103",
//       name: "Lost ball in carry",
//       total: "4",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Visit in opponents 22": {
//       event_id: "104",
//       name: "Visit in opponents 22",
//       total: "2",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Kick for territory": {
//       event_id: "105",
//       name: "Kick for territory",
//       total: "24",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "158",
//           subeventname: "Caught",
//           totalsubevent: "16",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "159",
//           subeventname: "Straight out",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "164",
//           subeventname: "Retrieved",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "165",
//           subeventname: "50-22",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "166",
//           subeventname: "Lineout",
//           totalsubevent: "5",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "185",
//           subeventname: "Dead Ball",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "186",
//           subeventname: "Knocked On",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "202",
//           subeventname: "Charged Down",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "340",
//           subeventname: "Half time",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "341",
//           subeventname: "Full Time",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     Ruck: {
//       event_id: "108",
//       name: "Ruck",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "334",
//           subeventname: "Less Than 3 Sec",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "335",
//           subeventname: "More Than 3 Sec",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Penalty Gain": {
//       event_id: "124",
//       name: "Penalty Gain",
//       total: "3",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "173",
//           subeventname: "Kick",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "174",
//           subeventname: "Tap",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "183",
//           subeventname: "Scrum",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "184",
//           subeventname: "Points",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Step out": {
//       event_id: "129",
//       name: "Step out",
//       total: "1",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     "Charge Down": {
//       event_id: "130",
//       name: "Charge Down",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Restart: {
//       event_id: "133",
//       name: "Restart",
//       total: "5",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "247",
//           subeventname: "kick off reception won",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "248",
//           subeventname: "kick off reception lost",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "249",
//           subeventname: "kick off retrieval won",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "250",
//           subeventname: "kick off retrieval lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "251",
//           subeventname: "false kick off",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "252",
//           subeventname: "goal line drop out reception won",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "253",
//           subeventname: "goal line drop out reception lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "254",
//           subeventname: "goal line drop out retrieval won",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "255",
//           subeventname: "goal line drop out retrieval lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "256",
//           subeventname: "goal line drop out straight out",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "257",
//           subeventname: "22 drop out reception won",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "258",
//           subeventname: "22 drop out reception lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "259",
//           subeventname: "22 drop out retrieval won",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "260",
//           subeventname: "22 drop out retrieval lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "261",
//           subeventname: "22 drop out straight out",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Visit in own 22": {
//       event_id: "139",
//       name: "Visit in own 22",
//       total: "0",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [],
//     },
//     Maul: {
//       event_id: "146",
//       name: "Maul",
//       total: "1",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "328",
//           subeventname: "Successful",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "329",
//           subeventname: "Unsuccessful",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Lineout throw": {
//       event_id: "151",
//       name: "Lineout throw",
//       total: "8",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "377",
//           subeventname: "Front won",
//           totalsubevent: "3",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "378",
//           subeventname: "Middle won",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "379",
//           subeventname: "Back won",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "380",
//           subeventname: "Front lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "381",
//           subeventname: "Middle lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "382",
//           subeventname: "Back lost",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "391",
//           subeventname: "Overthrow Won",
//           totalsubevent: "2",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "392",
//           subeventname: "Overthrow Lost",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Kick Reception": {
//       event_id: "158",
//       name: "Kick Reception",
//       total: "2",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "409",
//           subeventname: "Caught",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "410",
//           subeventname: "Knocked On",
//           totalsubevent: "0",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "411",
//           subeventname: "Knocked Back",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "412",
//           subeventname: "Missed",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//     "Lineout Pass to Receiver": {
//       event_id: "162",
//       name: "Lineout Pass to Receiver",
//       total: "5",
//       team: "820",
//       fixtureid: "6080",
//       "sub-event": [
//         {
//           subeventid: "419",
//           subeventname: "Complete",
//           totalsubevent: "3",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "420",
//           subeventname: "InComplete",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//         {
//           subeventid: "421",
//           subeventname: "No Pass",
//           totalsubevent: "1",
//           team: "820",
//           gameidid: "6080",
//         },
//       ],
//     },
//   },
//   scores: {
//     Home: 88,
//     Away: 5,
//   },
//   players: [],
//   cards: {
//     Homered: 0,
//     Awayred: 0,
//     Homeyellow: 0,
//     Awayyellow: 0,
//   },
//   fouls: {
//     Homewon: 0,
//     Awaywon: 0,
//     Homecommitted: 0,
//     Awaycommitted: 0,
//   },
//   standing: [],
//   gamedetails: [
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "12",
//       game_second: "7",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "12",
//       game_second: "42",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "15",
//       game_second: "48",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "16",
//       game_second: "37",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "17",
//       game_second: "57",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "18",
//       game_second: "50",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "23",
//       game_second: "1",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "23",
//       game_second: "35",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "31",
//       game_second: "16",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "30",
//       game_second: "52",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "39",
//       game_second: "59",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "40",
//       game_second: "49",
//       game_moment: "firsthalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "45",
//       game_second: "5",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "45",
//       game_second: "16",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "48",
//       game_second: "28",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "48",
//       game_second: "49",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "820",
//       gameid: "6080",
//       narration: "Score For South Coast Pirates",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "52",
//       game_second: "18",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "away",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "820",
//       gameid: "6080",
//       narration: "Score For South Coast Pirates",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "53",
//       game_second: "20",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "away",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "55",
//       game_second: "49",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "55",
//       game_second: "57",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "65",
//       game_second: "16",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "66",
//       game_second: "52",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "73",
//       game_second: "1",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "60",
//       subeventName: "Successful Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "73",
//       game_second: "48",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "75",
//       game_second: "29",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "820",
//       gameid: "6080",
//       narration: "Score For South Coast Pirates",
//       player_id: "0",
//       subevent_id: "61",
//       subeventName: "Missed Penalty",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "78",
//       game_second: "25",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "away",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "76",
//       game_second: "2",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "81",
//       game_second: "37",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "82",
//       game_second: "14",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "66",
//       subeventName: "Try",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "87",
//       game_second: "33",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//     {
//       event_name: "Score",
//       event_id: "49",
//       team: "246",
//       gameid: "6080",
//       narration: "Score For KCB 15s",
//       player_id: "0",
//       subevent_id: "42",
//       subeventName: "Missed Conversion",
//       subplayer_id: "",
//       subplayer_name: "",
//       game_minute: "88",
//       game_second: "35",
//       game_moment: "secondhalf",
//       teamplayer_id: "",
//       player_type: "",
//       pname: "",
//       Jersey_No: "",
//       subsubevent_id: "",
//       zone_id: "0",
//       tss: "home",
//     },
//   ],
// };
