import { calcBallPosession, getEvent, getSubEvent } from "@/lib/utils";
import React from "react";

const footballDetails = (
  home: Stats,
  away: Stats,
  details: FixtureDetails,
  scores: Scores
) => {
  const fixture = {} as Details;

  const possession = calcBallPosession(home, away);

  fixture["homeId"] = details.team1_id;
  fixture["awayId"] = details.team2_id;
  fixture["home"] = details.team1_name;
  fixture["away"] = details.team2_name;
  fixture["homeScore"] = scores.Home;
  fixture["awayScore"] = scores.Away;
  fixture["league"] = details.league;
  fixture["round"] = details.matchday;
  fixture["status"] = details.game_status;
  fixture["minute"] = details.minute;
  fixture["hPossession"] = possession.home;
  fixture["aPossession"] = possession.away;

  return fixture;
};

const footballAttack = (home: Stats, away: Stats) => {
  const attack = {} as FootballAttack;

  attack["keyPass"] = {
    home: getEvent(home, "98"),
    away: getEvent(away, "98"),
  };
  attack["setPiece"] = {
    home: getEvent(home, "161"),
    away: getEvent(away, "161"),
  };
  attack["freekick"] = {
    home: getSubEvent(home, "21", "398"),
    away: getSubEvent(away, "21", "398"),
  };
  attack["boxTouch"] = {
    home: getEvent(home, "155"),
    away: getEvent(away, "154"),
  };
  attack["boxCarry"] = {
    home: getEvent(home, "154"),
    away: getEvent(away, "154"),
  };
  attack["offside"] = {
    home: getEvent(home, "10"),
    away: getEvent(away, "10"),
  };
  attack["shotInBox"] = {
    home: {
      value: getSubEvent(home, "165", "422"),
      total: getEvent(home, "165"),
    },
    away: {
      value: getSubEvent(away, "165", "422"),
      total: getEvent(away, "165"),
    },
  };
  attack["shotOutBox"] = {
    home: {
      value: getSubEvent(home, "156", "405"),
      total: getEvent(home, "156"),
    },
    away: {
      value: getSubEvent(away, "156", "405"),
      total: getEvent(away, "156"),
    },
  };

  return attack;
};

const footballDiscipline = (fouls: Fouls, cards: Cards) => {
  const discipline = {} as FootballDiscipline;

  discipline["fouls"] = {
    home: fouls.Homecommitted,
    away: fouls.Awaycommitted,
  };
  discipline["cards"] = cards;

  return discipline;
};

const footballPassing = (home: Stats, away: Stats) => {
  const passing = {} as FootballPassing;

  passing["corner"] = { home: getEvent(home, "3"), away: getEvent(away, "3") };
  passing["ballLost"] = {
    home: getSubEvent(home, "67", "76"),
    away: getSubEvent(away, "67", "76"),
  };
  passing["ballWon"] = {
    home: getSubEvent(home, "67", "75"),
    away: getSubEvent(away, "67", "75"),
  };
  passing["throwIn"] = {
    home: getSubEvent(home, "12", "400"),
    away: getSubEvent(away, "12", "400"),
  };
  passing["longThrowIn"] = {
    home: getSubEvent(home, "12", "399"),
    away: getSubEvent(away, "12", "399"),
  };
  passing["pass"] = {
    home: {
      value: getEvent(home, "7"),
      total: getEvent(home, "25") + getEvent(home, "7"),
    },
    away: {
      value: getEvent(away, "7"),
      total: getEvent(away, "25") + getEvent(away, "7"),
    },
  };
  passing["progPass"] = {
    home: {
      value: getSubEvent(home, "95", "152"),
      total: getEvent(home, "95"),
    },
    away: {
      value: getSubEvent(away, "95", "152"),
      total: getEvent(away, "95"),
    },
  };
  passing["crossRight"] = {
    home: {
      value: getSubEvent(home, "159", "413"),
      total: getEvent(home, "159"),
    },
    away: {
      value: getSubEvent(away, "159", "413"),
      total: getEvent(away, "159"),
    },
  };
  passing["crossLeft"] = {
    home: {
      value: getSubEvent(home, "166", "426"),
      total: getEvent(home, "166"),
    },
    away: {
      value: getSubEvent(away, "166", "426"),
      total: getEvent(away, "166"),
    },
  };

  return passing;
};

const footballDuels = (home: Stats, away: Stats) => {
  const duels = {} as FootballDuels;

  duels["aerial"] = {
    home: {
      value: getSubEvent(home, "93", "144"),
      total: getEvent(home, "93"),
    },
    away: {
      value: getSubEvent(away, "93", "144"),
      total: getEvent(away, "93"),
    },
  };

  duels["ground"] = {
    home: {
      value: getSubEvent(home, "94", "146"),
      total: getEvent(home, "94"),
    },
    away: {
      value: getSubEvent(away, "94", "146"),
      total: getEvent(away, "94"),
    },
  };

  return duels;
};

const footballDefense = (home: Stats, away: Stats) => {
  const defense = {} as FootballDefense;

  defense["clearance"] = {
    home: getEvent(home, "26"),
    away: getEvent(away, "26"),
  };
  defense["blocks"] = {
    home: getEvent(home, "27"),
    away: getEvent(away, "27"),
  };
  defense["foulWon"] = {
    home: getSubEvent(home, "11", "73"),
    away: getSubEvent(away, "11", "73"),
  };
  defense["intercptOwn"] = {
    home: getSubEvent(home, "28", "403"),
    away: getSubEvent(away, "28", "403"),
  };
  defense["intercptOpp"] = {
    home: getSubEvent(home, "28", "404"),
    away: getSubEvent(away, "28", "404"),
  };
  defense["tackles"] = {
    home: {
      value: getSubEvent(home, "97", "156"),
      total: getEvent(home, "97"),
    },
    away: {
      value: getSubEvent(away, "97", "156"),
      total: getEvent(away, "97"),
    },
  };

  return defense;
};

const footballGK = (home: Stats, away: Stats) => {
  const gk = {} as FootballGK;

  gk["saves"] = {
    home: getEvent(home, "24"),
    away: getEvent(away, "24"),
  };
  gk["runOuts"] = {
    home: getEvent(home, "32"),
    away: getEvent(away, "32"),
  };
  gk["kickOuts"] = {
    home: getEvent(home, "142"),
    away: getEvent(away, "142"),
  };
  gk["throwOuts"] = {
    home: getEvent(home, "68"),
    away: getEvent(away, "68"),
  };
  gk["claims"] = {
    home: {
      value: getSubEvent(home, "69", "80") + getSubEvent(home, "69", "81"),
      total: getEvent(home, "69"),
    },
    away: {
      value: getSubEvent(away, "69", "80") + getSubEvent(away, "69", "81"),
      total: getEvent(away, "69"),
    },
  };
  gk["goalkick"] = {
    home: {
      value: getEvent(home, "167"),
      total: getEvent(home, "167") + getEvent(home, "168"),
    },
    away: {
      value: getEvent(away, "167"),
      total: getEvent(away, "167") + getEvent(away, "168"),
    },
  };

  return gk;
};

const LeaguesPage = () => {
  const footballData = (data: FixtureData) => {
    const details = data["fixture"][0];
    const scores = data["scores"];
    const home = data["home"];
    const away = data["away"];
    const fouls = data["fouls"];
    const cards = data["cards"];

    const footballData = {} as FootballData;

    footballData["details"] = footballDetails(home, away, details, scores);
    footballData["attack"] = footballAttack(home, away);
    footballData["discipline"] = footballDiscipline(fouls, cards);
    footballData["passing"] = footballPassing(home, away);
    footballData["duels"] = footballDuels(home, away);
    footballData["defense"] = footballDefense(home, away);
    footballData["gk"] = footballGK(home, away);

    // console.log(rugbyData);
    return footballData;
  };

  const xData = footballData(data);

  console.log(xData);

  return <div>{JSON.stringify(xData)}</div>;
};

export default LeaguesPage;

const data: FixtureData = {
  fixture: [
    {
      id: "5216",
      team1_id: "76",
      team2_id: "1",
      game_date: "2024-09-14",
      team1_name: "Nairobi City Stars",
      team2_name: "Bidco United",
      game_status: "ended",
      minute: "101",
      second: "25",
      game_moment: "secondhalf",
      league: "FKF Premier League",
      matchday: "2",
      fixture_type: "football",
      live: "1",
      teamview: "0",
      series: "14",
      leagueid: "1",
      home_score: "1",
      away_score: "1",
      winner: null,
      start_app: "1",
      hybrid: "0",
      hybridhome: null,
      hybridaway: null,
      lite: "0",
      location_id: "0",
      category: "1",
      groupid: "1",
      matchtime: "13:00",
      tmvplayer: "0",
    },
  ],
  home: {
    Penalty: {
      event_id: "1",
      name: "Penalty",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "150",
          subeventname: "Won",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "151",
          subeventname: "Miss",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "304",
          subeventname: "Conceded",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Corner: {
      event_id: "3",
      name: "Corner",
      total: "3",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "6",
          subeventname: "Inswinging",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "7",
          subeventname: "Outswinging",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "8",
          subeventname: "Short Corner",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Card: {
      event_id: "5",
      name: "Card",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "21",
          subeventname: "Yellow",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "22",
          subeventname: "Red",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Pass: {
      event_id: "7",
      name: "Pass",
      total: "227",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Offside: {
      event_id: "10",
      name: "Offside",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Foul: {
      event_id: "11",
      name: "Foul",
      total: "28",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "73",
          subeventname: "Won",
          totalsubevent: "14",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "74",
          subeventname: "Committed",
          totalsubevent: "14",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Throw in": {
      event_id: "12",
      name: "Throw in",
      total: "14",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "399",
          subeventname: "Long",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "400",
          subeventname: "Normal",
          totalsubevent: "14",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Goal Kick": {
      event_id: "15",
      name: "Goal Kick",
      total: "15",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "432",
          subeventname: "Short GK",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "433",
          subeventname: "Long GK",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Substitute: {
      event_id: "17",
      name: "Substitute",
      total: "5",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Goal: {
      event_id: "19",
      name: "Goal",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "9",
          subeventname: "Open Play",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "10",
          subeventname: "Corner",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "11",
          subeventname: "Free Kick",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "12",
          subeventname: "Counter",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "13",
          subeventname: "Throw in",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "14",
          subeventname: "Penalty",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "148",
          subeventname: "Transition",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "305",
          subeventname: "Penalty rebound",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    OG: {
      event_id: "20",
      name: "OG",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Freekick: {
      event_id: "21",
      name: "Freekick",
      total: "4",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "397",
          subeventname: "Taker",
          totalsubevent: "2",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "398",
          subeventname: "Won",
          totalsubevent: "2",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Assists: {
      event_id: "23",
      name: "Assists",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Save: {
      event_id: "24",
      name: "Save",
      total: "3",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "19",
          subeventname: "Penalty Save",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "20",
          subeventname: "Normal Save",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Incomplete Pass": {
      event_id: "25",
      name: "Incomplete Pass",
      total: "62",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Clearances: {
      event_id: "26",
      name: "Clearances",
      total: "15",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Blocks: {
      event_id: "27",
      name: "Blocks",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    Interceptions: {
      event_id: "28",
      name: "Interceptions",
      total: "8",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "403",
          subeventname: "Own half",
          totalsubevent: "6",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "404",
          subeventname: "Opp half",
          totalsubevent: "2",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Goal Conceded": {
      event_id: "31",
      name: "Goal Conceded",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "25",
          subeventname: "Open Play",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "26",
          subeventname: "Corner",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "27",
          subeventname: "Freekick",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "28",
          subeventname: "Counter",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "29",
          subeventname: "Throw in",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "30",
          subeventname: "Penalty",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "149",
          subeventname: "Transition",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "306",
          subeventname: "Penalty rebound",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Run-outs": {
      event_id: "32",
      name: "Run-outs",
      total: "1",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "34",
          subeventname: "Successfully",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "35",
          subeventname: "Unsuccessfully",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Ball: {
      event_id: "67",
      name: "Ball",
      total: "35",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "75",
          subeventname: "Won",
          totalsubevent: "12",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "76",
          subeventname: "Lost",
          totalsubevent: "23",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Throw-out": {
      event_id: "68",
      name: "Throw-out",
      total: "8",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "77",
          subeventname: "Complete",
          totalsubevent: "8",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "78",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Claims: {
      event_id: "69",
      name: "Claims",
      total: "6",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "79",
          subeventname: "Miss",
          totalsubevent: "2",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "80",
          subeventname: "GK Catch",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "81",
          subeventname: "Punch",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "82",
          subeventname: "Drop",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Aerial Duels": {
      event_id: "93",
      name: "Aerial Duels",
      total: "9",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "143",
          subeventname: "Lost",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "144",
          subeventname: "Won",
          totalsubevent: "6",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Ground Duels": {
      event_id: "94",
      name: "Ground Duels",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "145",
          subeventname: "Lost",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "146",
          subeventname: "Won",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Progress Pass": {
      event_id: "95",
      name: "Progress Pass",
      total: "11",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "152",
          subeventname: "Complete",
          totalsubevent: "6",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "153",
          subeventname: "Incomplete",
          totalsubevent: "5",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Dribbles: {
      event_id: "96",
      name: "Dribbles",
      total: "6",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "154",
          subeventname: "Complete",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "155",
          subeventname: "Incomplete",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    Tackle: {
      event_id: "97",
      name: "Tackle",
      total: "19",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "156",
          subeventname: "Won",
          totalsubevent: "12",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "157",
          subeventname: "Lost",
          totalsubevent: "7",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Key Pass": {
      event_id: "98",
      name: "Key Pass",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Kick-outs": {
      event_id: "142",
      name: "Kick-outs",
      total: "4",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "307",
          subeventname: "Complete",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "308",
          subeventname: "Incomplete",
          totalsubevent: "3",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "PM Penalties": {
      event_id: "143",
      name: "PM Penalties",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "309",
          subeventname: "Scored",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "310",
          subeventname: "Missed",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Cross Against": {
      event_id: "153",
      name: "Cross Against",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "401",
          subeventname: "From left",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "402",
          subeventname: "From right",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Box Carry": {
      event_id: "154",
      name: "Box Carry",
      total: "3",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Box Touch": {
      event_id: "155",
      name: "Box Touch",
      total: "12",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Shot Out-box": {
      event_id: "156",
      name: "Shot Out-box",
      total: "5",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "405",
          subeventname: "On Target",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "406",
          subeventname: "Off Target",
          totalsubevent: "4",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "407",
          subeventname: "Blocked",
          totalsubevent: "1",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Cross Right": {
      event_id: "159",
      name: "Cross Right",
      total: "6",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "413",
          subeventname: "Complete",
          totalsubevent: "2",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "414",
          subeventname: "Incomplete",
          totalsubevent: "4",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "415",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Ground Pass": {
      event_id: "160",
      name: "Ground Pass",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Set-piece Chance": {
      event_id: "161",
      name: "Set-piece Chance",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "416",
          subeventname: "Freekick",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "417",
          subeventname: "Corner",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "418",
          subeventname: "Throw-in",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Shot In-box": {
      event_id: "165",
      name: "Shot In-box",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "422",
          subeventname: "On Target",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "423",
          subeventname: "Off Target",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "424",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Cross Left": {
      event_id: "166",
      name: "Cross Left",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "425",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "426",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "427",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Short GK": {
      event_id: "167",
      name: "Short GK",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "428",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "430",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
    "Long GK": {
      event_id: "168",
      name: "Long GK",
      total: "0",
      team: "76",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "429",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
        {
          subeventid: "431",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "76",
          gameidid: "5216",
        },
      ],
    },
  },
  away: {
    Penalty: {
      event_id: "1",
      name: "Penalty",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "150",
          subeventname: "Won",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "151",
          subeventname: "Miss",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "304",
          subeventname: "Conceded",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Corner: {
      event_id: "3",
      name: "Corner",
      total: "7",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "6",
          subeventname: "Inswinging",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "7",
          subeventname: "Outswinging",
          totalsubevent: "6",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "8",
          subeventname: "Short Corner",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Card: {
      event_id: "5",
      name: "Card",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "21",
          subeventname: "Yellow",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "22",
          subeventname: "Red",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Pass: {
      event_id: "7",
      name: "Pass",
      total: "268",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Offside: {
      event_id: "10",
      name: "Offside",
      total: "3",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Foul: {
      event_id: "11",
      name: "Foul",
      total: "24",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "73",
          subeventname: "Won",
          totalsubevent: "11",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "74",
          subeventname: "Committed",
          totalsubevent: "13",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Throw in": {
      event_id: "12",
      name: "Throw in",
      total: "35",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "399",
          subeventname: "Long",
          totalsubevent: "2",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "400",
          subeventname: "Normal",
          totalsubevent: "33",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Goal Kick": {
      event_id: "15",
      name: "Goal Kick",
      total: "4",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "432",
          subeventname: "Short GK",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "433",
          subeventname: "Long GK",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Substitute: {
      event_id: "17",
      name: "Substitute",
      total: "4",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Goal: {
      event_id: "19",
      name: "Goal",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "9",
          subeventname: "Open Play",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "10",
          subeventname: "Corner",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "11",
          subeventname: "Free Kick",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "12",
          subeventname: "Counter",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "13",
          subeventname: "Throw in",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "14",
          subeventname: "Penalty",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "148",
          subeventname: "Transition",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "305",
          subeventname: "Penalty rebound",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    OG: {
      event_id: "20",
      name: "OG",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Freekick: {
      event_id: "21",
      name: "Freekick",
      total: "6",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "397",
          subeventname: "Taker",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "398",
          subeventname: "Won",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Assists: {
      event_id: "23",
      name: "Assists",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Save: {
      event_id: "24",
      name: "Save",
      total: "3",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "19",
          subeventname: "Penalty Save",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "20",
          subeventname: "Normal Save",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Incomplete Pass": {
      event_id: "25",
      name: "Incomplete Pass",
      total: "48",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Clearances: {
      event_id: "26",
      name: "Clearances",
      total: "8",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Blocks: {
      event_id: "27",
      name: "Blocks",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    Interceptions: {
      event_id: "28",
      name: "Interceptions",
      total: "12",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "403",
          subeventname: "Own half",
          totalsubevent: "9",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "404",
          subeventname: "Opp half",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Goal Conceded": {
      event_id: "31",
      name: "Goal Conceded",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "25",
          subeventname: "Open Play",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "26",
          subeventname: "Corner",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "27",
          subeventname: "Freekick",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "28",
          subeventname: "Counter",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "29",
          subeventname: "Throw in",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "30",
          subeventname: "Penalty",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "149",
          subeventname: "Transition",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "306",
          subeventname: "Penalty rebound",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Run-outs": {
      event_id: "32",
      name: "Run-outs",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "34",
          subeventname: "Successfully",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "35",
          subeventname: "Unsuccessfully",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Ball: {
      event_id: "67",
      name: "Ball",
      total: "41",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "75",
          subeventname: "Won",
          totalsubevent: "14",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "76",
          subeventname: "Lost",
          totalsubevent: "27",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Throw-out": {
      event_id: "68",
      name: "Throw-out",
      total: "8",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "77",
          subeventname: "Complete",
          totalsubevent: "8",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "78",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Claims: {
      event_id: "69",
      name: "Claims",
      total: "4",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "79",
          subeventname: "Miss",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "80",
          subeventname: "GK Catch",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "81",
          subeventname: "Punch",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "82",
          subeventname: "Drop",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Aerial Duels": {
      event_id: "93",
      name: "Aerial Duels",
      total: "7",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "143",
          subeventname: "Lost",
          totalsubevent: "5",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "144",
          subeventname: "Won",
          totalsubevent: "2",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Ground Duels": {
      event_id: "94",
      name: "Ground Duels",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "145",
          subeventname: "Lost",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "146",
          subeventname: "Won",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Progress Pass": {
      event_id: "95",
      name: "Progress Pass",
      total: "11",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "152",
          subeventname: "Complete",
          totalsubevent: "5",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "153",
          subeventname: "Incomplete",
          totalsubevent: "6",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Dribbles: {
      event_id: "96",
      name: "Dribbles",
      total: "7",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "154",
          subeventname: "Complete",
          totalsubevent: "5",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "155",
          subeventname: "Incomplete",
          totalsubevent: "2",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    Tackle: {
      event_id: "97",
      name: "Tackle",
      total: "6",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "156",
          subeventname: "Won",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "157",
          subeventname: "Lost",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Key Pass": {
      event_id: "98",
      name: "Key Pass",
      total: "8",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Kick-outs": {
      event_id: "142",
      name: "Kick-outs",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "307",
          subeventname: "Complete",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "308",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "PM Penalties": {
      event_id: "143",
      name: "PM Penalties",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "309",
          subeventname: "Scored",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "310",
          subeventname: "Missed",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Cross Against": {
      event_id: "153",
      name: "Cross Against",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "401",
          subeventname: "From left",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "402",
          subeventname: "From right",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Box Carry": {
      event_id: "154",
      name: "Box Carry",
      total: "1",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Box Touch": {
      event_id: "155",
      name: "Box Touch",
      total: "10",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Shot Out-box": {
      event_id: "156",
      name: "Shot Out-box",
      total: "5",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "405",
          subeventname: "On Target",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "406",
          subeventname: "Off Target",
          totalsubevent: "3",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "407",
          subeventname: "Blocked",
          totalsubevent: "1",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Cross Right": {
      event_id: "159",
      name: "Cross Right",
      total: "14",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "413",
          subeventname: "Complete",
          totalsubevent: "2",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "414",
          subeventname: "Incomplete",
          totalsubevent: "12",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "415",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Ground Pass": {
      event_id: "160",
      name: "Ground Pass",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [],
    },
    "Set-piece Chance": {
      event_id: "161",
      name: "Set-piece Chance",
      total: "2",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "416",
          subeventname: "Freekick",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "417",
          subeventname: "Corner",
          totalsubevent: "2",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "418",
          subeventname: "Throw-in",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Shot In-box": {
      event_id: "165",
      name: "Shot In-box",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "422",
          subeventname: "On Target",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "423",
          subeventname: "Off Target",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "424",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Cross Left": {
      event_id: "166",
      name: "Cross Left",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "425",
          subeventname: "Blocked",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "426",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "427",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Short GK": {
      event_id: "167",
      name: "Short GK",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "428",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "430",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
    "Long GK": {
      event_id: "168",
      name: "Long GK",
      total: "0",
      team: "1",
      fixtureid: "5216",
      "sub-event": [
        {
          subeventid: "429",
          subeventname: "Complete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
        {
          subeventid: "431",
          subeventname: "Incomplete",
          totalsubevent: "0",
          team: "1",
          gameidid: "5216",
        },
      ],
    },
  },
  scores: {
    Home: "1",
    Away: "1",
  },
  players: [
    {
      id: "76031",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4044",
      Jersey_No: "12",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3914",
      teamId: "76",
      pname: "Edwin  Mukolwe ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1",
      red: "0",
      GK: "1",
    },
    {
      id: "76047",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4011",
      Jersey_No: "21",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3884",
      teamId: "1",
      pname: " John Otieno  ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1",
      red: "0",
      GK: "1",
    },
    {
      id: "76055",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4016",
      Jersey_No: "11",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3889",
      teamId: "1",
      pname: "Eugine Ikutwa ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "2",
      red: "0",
      GK: "0",
    },
    {
      id: "76035",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "3733",
      Jersey_No: "27",
      system_user_id: "95",
      player_type: "first11",
      player_id: "3610",
      teamId: "76",
      pname: "Gilbert  Abala ",
      last_updated: "2024-10-23 15:29:21",
      lineupposition: "2",
      red: "0",
      GK: "0",
    },
    {
      id: "76063",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10986",
      Jersey_No: "15",
      system_user_id: "7",
      player_type: "first11",
      player_id: "10258",
      teamId: "1",
      pname: "Marvin  Amuka Ochieng",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "3",
      red: "0",
      GK: "0",
    },
    {
      id: "76043",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "1158",
      Jersey_No: "22",
      system_user_id: "7",
      player_type: "first11",
      player_id: "1217",
      teamId: "76",
      pname: "Timothy Oduor ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "3",
      red: "0",
      GK: "0",
    },
    {
      id: "76029",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "765",
      Jersey_No: "8",
      system_user_id: "7",
      player_type: "first11",
      player_id: "110",
      teamId: "76",
      pname: "Calvin Masawa ",
      last_updated: "2024-09-14 14:14:01",
      lineupposition: "4",
      red: "0",
      GK: "0",
    },
    {
      id: "76052",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "2",
      Jersey_No: "4",
      system_user_id: "7",
      player_type: "first11",
      player_id: "2",
      teamId: "1",
      pname: "David Kalama ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "4",
      red: "0",
      GK: "0",
    },
    {
      id: "76066",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4013",
      Jersey_No: "3",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3886",
      teamId: "1",
      pname: "Thomas Wainaina ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "5",
      red: "0",
      GK: "0",
    },
    {
      id: "76045",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "3820",
      Jersey_No: "15",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3692",
      teamId: "76",
      pname: "Wycliffe Omondi  ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "5",
      red: "0",
      GK: "0",
    },
    {
      id: "76036",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10478",
      Jersey_No: "14",
      system_user_id: "7",
      player_type: "first11",
      player_id: "9756",
      teamId: "76",
      pname: "James Ssemambo ",
      last_updated: "2024-09-14 14:25:00",
      lineupposition: "6",
      red: "0",
      GK: "0",
    },
    {
      id: "76057",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10989",
      Jersey_No: "37",
      system_user_id: "7",
      player_type: "first11",
      player_id: "10261",
      teamId: "1",
      pname: "John Oruko ",
      last_updated: "2024-09-14 14:32:49",
      lineupposition: "6",
      red: "0",
      GK: "0",
    },
    {
      id: "76064",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4015",
      Jersey_No: "10",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3888",
      teamId: "1",
      pname: "Michael Omondi ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "7",
      red: "0",
      GK: "0",
    },
    {
      id: "76028",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "3819",
      Jersey_No: "0",
      system_user_id: "7",
      player_type: "first11",
      player_id: "952",
      teamId: "76",
      pname: "Brian Mzee ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "7",
      red: "0",
      GK: "0",
    },
    {
      id: "76056",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "7",
      Jersey_No: "2",
      system_user_id: "7",
      player_type: "first11",
      player_id: "7",
      teamId: "1",
      pname: "Jacob Anyango ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "8",
      red: "0",
      GK: "0",
    },
    {
      id: "76042",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "769",
      Jersey_No: "3",
      system_user_id: "95",
      player_type: "first11",
      player_id: "101",
      teamId: "76",
      pname: "Sven Yidah ",
      last_updated: "2024-10-23 15:38:24",
      lineupposition: "8",
      red: "0",
      GK: "0",
    },
    {
      id: "76039",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "5686",
      Jersey_No: "24",
      system_user_id: "7",
      player_type: "first11",
      player_id: "5422",
      teamId: "76",
      pname: "Rodgers  Obusu ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "9",
      red: "0",
      GK: "0",
    },
    {
      id: "76050",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4008",
      Jersey_No: "33",
      system_user_id: "7",
      player_type: "first11",
      player_id: "3881",
      teamId: "1",
      pname: "Chris Opondo ",
      last_updated: "2024-09-14 14:16:38",
      lineupposition: "9",
      red: "0",
      GK: "0",
    },
    {
      id: "76030",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "1993",
      Jersey_No: "10",
      system_user_id: "95",
      player_type: "first11",
      player_id: "2019",
      teamId: "76",
      pname: "Dennis Oalo ",
      last_updated: "2024-10-23 15:38:42",
      lineupposition: "10",
      red: "0",
      GK: "0",
    },
    {
      id: "76048",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10987",
      Jersey_No: "8",
      system_user_id: "7",
      player_type: "first11",
      player_id: "10259",
      teamId: "1",
      pname: "Abdalla  Bwire ",
      last_updated: "2024-09-14 14:32:49",
      lineupposition: "10",
      red: "0",
      GK: "0",
    },
    {
      id: "76058",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4582",
      Jersey_No: "35",
      system_user_id: "7",
      player_type: "first11",
      player_id: "4429",
      teamId: "1",
      pname: "John Owira ",
      last_updated: "2024-09-14 14:45:17",
      lineupposition: "11",
      red: "0",
      GK: "0",
    },
    {
      id: "76033",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "779",
      Jersey_No: "16",
      system_user_id: "95",
      player_type: "first11",
      player_id: "828",
      teamId: "76",
      pname: "Elvis Noor ",
      last_updated: "2024-10-23 14:05:28",
      lineupposition: "11",
      red: "0",
      GK: "0",
    },
    {
      id: "76061",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4012",
      Jersey_No: "1",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3885",
      teamId: "1",
      pname: "Malvin  Nderitu ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76059",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10988",
      Jersey_No: "99",
      system_user_id: "7",
      player_type: "sub",
      player_id: "10260",
      teamId: "1",
      pname: "Kevin  Msamali ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76060",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10342",
      Jersey_No: "55",
      system_user_id: "7",
      player_type: "sub",
      player_id: "9620",
      teamId: "1",
      pname: "Maliachi Makari ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76032",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "759",
      Jersey_No: "12",
      system_user_id: "7",
      player_type: "sub",
      player_id: "836",
      teamId: "76",
      pname: "Edwin Buliba ",
      last_updated: "2024-09-14 14:14:01",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76062",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4007",
      Jersey_No: "30",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3880",
      teamId: "1",
      pname: "Martin  Nderitu ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76065",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4009",
      Jersey_No: "24",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3882",
      teamId: "1",
      pname: "Samuel Ndungu ",
      last_updated: "2024-09-14 14:45:17",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76027",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10479",
      Jersey_No: "28",
      system_user_id: "95",
      player_type: "sub",
      player_id: "9757",
      teamId: "76",
      pname: "Andre Kalama ",
      last_updated: "2024-10-23 15:22:50",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76054",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4017",
      Jersey_No: "12",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3890",
      teamId: "1",
      pname: "Eric Michubu ",
      last_updated: "2024-09-14 14:16:38",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76053",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4014",
      Jersey_No: "8",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3887",
      teamId: "1",
      pname: "Doughlas Mokaya ",
      last_updated: "2024-09-14 14:32:49",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76037",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "783",
      Jersey_No: "11",
      system_user_id: "95",
      player_type: "sub",
      player_id: "843",
      teamId: "76",
      pname: "Mohammed Bajaber ",
      last_updated: "2024-10-23 14:02:59",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76051",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4564",
      Jersey_No: "20",
      system_user_id: "7",
      player_type: "sub",
      player_id: "4417",
      teamId: "1",
      pname: "Clinton Asiago ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76049",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "4565",
      Jersey_No: "21",
      system_user_id: "7",
      player_type: "sub",
      player_id: "4418",
      teamId: "1",
      pname: "Brian Mboya ",
      last_updated: "2024-09-14 14:32:49",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76046",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "3818",
      Jersey_No: "21",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3691",
      teamId: "76",
      pname: "Yuto Kasaba ",
      last_updated: "2024-09-14 14:25:00",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76034",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "780",
      Jersey_No: "1",
      system_user_id: "7",
      player_type: "sub",
      player_id: "827",
      teamId: "76",
      pname: "Elvis Ochoro ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76044",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "2047",
      Jersey_No: "19",
      system_user_id: "53",
      player_type: "sub",
      player_id: "2074",
      teamId: "76",
      pname: "Vincent  Owino ",
      last_updated: "2024-09-21 16:31:14",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76041",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "10627",
      Jersey_No: "15",
      system_user_id: "7",
      player_type: "sub",
      player_id: "9905",
      teamId: "76",
      pname: "Steve Bulungu ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76040",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "782",
      Jersey_No: "14",
      system_user_id: "7",
      player_type: "sub",
      player_id: "842",
      teamId: "76",
      pname: "Rowland Makati ",
      last_updated: "2024-09-14 14:39:13",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
    {
      id: "76038",
      fixture_id: "5216",
      date_created: "2024-09-14 12:54:32",
      team_player_id: "3727",
      Jersey_No: "5",
      system_user_id: "7",
      player_type: "sub",
      player_id: "3604",
      teamId: "76",
      pname: "Robinson  Asenwa ",
      last_updated: "2024-09-14 12:54:32",
      lineupposition: "1000",
      red: "0",
      GK: "0",
    },
  ],
  cards: {
    Homered: 0,
    Awayred: 0,
    Homeyellow: 1,
    Awayyellow: 1,
  },
  fouls: {
    Homewon: 14,
    Awaywon: 11,
    Homecommitted: 14,
    Awaycommitted: 13,
  },
  standing: [],
  gamedetails: [
    {
      event_name: "Goal Conceded",
      event_id: "31",
      team: "1",
      gameid: "5216",
      narration: "Goal Conceded For Bidco United",
      player_id: "3884",
      subevent_id: "149",
      subeventName: "Transition",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "2",
      game_second: "14",
      game_moment: "firsthalf",
      teamplayer_id: "4011",
      player_type: "first11",
      pname: " John Otieno  ",
      Jersey_No: "21",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Goal",
      event_id: "19",
      team: "76",
      gameid: "5216",
      narration: "Goal For Nairobi City Stars",
      player_id: "3691",
      subevent_id: "148",
      subeventName: "Transition",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "1",
      game_second: "34",
      game_moment: "firsthalf",
      teamplayer_id: "3818",
      player_type: "first11",
      pname: "Yuto Kasaba ",
      Jersey_No: "21",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Card",
      event_id: "5",
      team: "1",
      gameid: "5216",
      narration: "Card For Bidco United",
      player_id: "3889",
      subevent_id: "21",
      subeventName: "Yellow",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "9",
      game_second: "10",
      game_moment: "firsthalf",
      teamplayer_id: "4016",
      player_type: "first11",
      pname: "Eugine Ikutwa ",
      Jersey_No: "11",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "76",
      gameid: "5216",
      narration: "Substitute For Nairobi City Stars",
      player_id: "836",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "110",
      subplayer_name: "Calvin Masawa ",
      game_minute: "52",
      game_second: "57",
      game_moment: "secondhalf",
      teamplayer_id: "759",
      player_type: "first11",
      pname: "Edwin Buliba ",
      Jersey_No: "12",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "1",
      gameid: "5216",
      narration: "Substitute For Bidco United",
      player_id: "3890",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "3881",
      subplayer_name: "Chris Opondo ",
      game_minute: "59",
      game_second: "39",
      game_moment: "secondhalf",
      teamplayer_id: "4017",
      player_type: "first11",
      pname: "Eric Michubu ",
      Jersey_No: "12",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "76",
      gameid: "5216",
      narration: "Substitute For Nairobi City Stars",
      player_id: "2074",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "9756",
      subplayer_name: "James Ssemambo ",
      game_minute: "66",
      game_second: "21",
      game_moment: "secondhalf",
      teamplayer_id: "2047",
      player_type: "first11",
      pname: "Vincent  Owino ",
      Jersey_No: "13",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "76",
      gameid: "5216",
      narration: "Substitute For Nairobi City Stars",
      player_id: "3691",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "2019",
      subplayer_name: "Dennis Oalo ",
      game_minute: "66",
      game_second: "26",
      game_moment: "secondhalf",
      teamplayer_id: "3818",
      player_type: "first11",
      pname: "Yuto Kasaba ",
      Jersey_No: "21",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "1",
      gameid: "5216",
      narration: "Substitute For Bidco United",
      player_id: "3887",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "10259",
      subplayer_name: "Abdalla  Bwire ",
      game_minute: "75",
      game_second: "17",
      game_moment: "secondhalf",
      teamplayer_id: "4014",
      player_type: "first11",
      pname: "Doughlas Mokaya ",
      Jersey_No: "8",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "1",
      gameid: "5216",
      narration: "Substitute For Bidco United",
      player_id: "4418",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "10261",
      subplayer_name: "Cliff Oruko ",
      game_minute: "75",
      game_second: "28",
      game_moment: "secondhalf",
      teamplayer_id: "4565",
      player_type: "first11",
      pname: "Brian Mboya ",
      Jersey_No: "21",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "76",
      gameid: "5216",
      narration: "Substitute For Nairobi City Stars",
      player_id: "842",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "3610",
      subplayer_name: "Gilbert  Abala ",
      game_minute: "83",
      game_second: "27",
      game_moment: "secondhalf",
      teamplayer_id: "782",
      player_type: "first11",
      pname: "Rowland Makati ",
      Jersey_No: "14",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "76",
      gameid: "5216",
      narration: "Substitute For Nairobi City Stars",
      player_id: "843",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "828",
      subplayer_name: "Elvis Noor ",
      game_minute: "83",
      game_second: "37",
      game_moment: "secondhalf",
      teamplayer_id: "783",
      player_type: "first11",
      pname: "Mohammed Bajaber ",
      Jersey_No: "18",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Goal",
      event_id: "19",
      team: "1",
      gameid: "5216",
      narration: "Goal For Bidco United",
      player_id: "3889",
      subevent_id: "11",
      subeventName: "Free Kick",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "83",
      game_second: "47",
      game_moment: "secondhalf",
      teamplayer_id: "4016",
      player_type: "first11",
      pname: "Eugine Ikutwa ",
      Jersey_No: "11",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
    {
      event_name: "Goal Conceded",
      event_id: "31",
      team: "76",
      gameid: "5216",
      narration: "Goal Conceded For Nairobi City Stars",
      player_id: "3914",
      subevent_id: "27",
      subeventName: "Freekick",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "85",
      game_second: "8",
      game_moment: "secondhalf",
      teamplayer_id: "4044",
      player_type: "first11",
      pname: "Edwin  Mukolwe ",
      Jersey_No: "12",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Card",
      event_id: "5",
      team: "76",
      gameid: "5216",
      narration: "Card For Nairobi City Stars",
      player_id: "9756",
      subevent_id: "21",
      subeventName: "Yellow",
      subplayer_id: "",
      subplayer_name: "",
      game_minute: "84",
      game_second: "28",
      game_moment: "secondhalf",
      teamplayer_id: "10478",
      player_type: "sub",
      pname: "James Ssemambo ",
      Jersey_No: "14",
      subsubevent_id: "",
      zone_id: null,
      tss: "home",
    },
    {
      event_name: "Substitute",
      event_id: "17",
      team: "1",
      gameid: "5216",
      narration: "Substitute For Bidco United",
      player_id: "3882",
      subevent_id: "",
      subeventName: "",
      subplayer_id: "4429",
      subplayer_name: "John Owira ",
      game_minute: "86",
      game_second: "33",
      game_moment: "secondhalf",
      teamplayer_id: "4009",
      player_type: "first11",
      pname: "Samuel Ndungu ",
      Jersey_No: "24",
      subsubevent_id: "",
      zone_id: null,
      tss: "away",
    },
  ],
};
